In [4]:
from pathlib import Path
import pandas as pd
import numpy as np

In [5]:
DATA_DIR = Path(r"C:\Users\admin\Desktop\HWU\ResearchMethods\MachineLearningCVE")

csv_files = sorted(DATA_DIR.glob("*.csv"))

print(f"Found {len(csv_files)} CSV files:")

for file in csv_files:
    print(file.name)

Found 8 CSV files:
Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv
Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv
Friday-WorkingHours-Morning.pcap_ISCX.csv
Monday-WorkingHours.pcap_ISCX.csv
Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv
Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv
Tuesday-WorkingHours.pcap_ISCX.csv
Wednesday-workingHours.pcap_ISCX.csv

In [6]:
sample = pd.read_csv(csv_files[0], nrows=5)

print(sample)

    Destination Port   Flow Duration   Total Fwd Packets  \
0              54865               3                   2
1              55054             109                   1
2              55055              52                   1
3              46236              34                   1
4              54863               3                   2

    Total Backward Packets  Total Length of Fwd Packets  \
0                        0                           12
1                        1                            6
2                        1                            6
3                        1                            6
4                        0                           12

    Total Length of Bwd Packets   Fwd Packet Length Max  \
0                             0                       6
1                             6                       6
2                             6                       6
3                             6                       6
4                             0                       6

    Fwd Packet Length Min   Fwd Packet Length Mean   Fwd Packet Length Std  \
0                       6                        6                       0
1                       6                        6                       0
2                       6                        6                       0
3                       6                        6                       0
4                       6                        6                       0

   ...   min_seg_size_forward  Active Mean   Active Std   Active Max  \
0  ...                     20            0            0            0
1  ...                     20            0            0            0
2  ...                     20            0            0            0
3  ...                     20            0            0            0
4  ...                     20            0            0            0

    Active Min  Idle Mean   Idle Std   Idle Max   Idle Min   Label
0            0          0          0          0          0  BENIGN
1            0          0          0          0          0  BENIGN
2            0          0          0          0          0  BENIGN
3            0          0          0          0          0  BENIGN
4            0          0          0          0          0  BENIGN

[5 rows x 79 columns]

In [7]:
print(f"Number of columns: {len(sample.columns)}")

for i, column in enumerate(sample.columns, start=1):
    print(f"{i}: {column}")

Number of columns: 79
1:  Destination Port
2:  Flow Duration
3:  Total Fwd Packets
4:  Total Backward Packets
5: Total Length of Fwd Packets
6:  Total Length of Bwd Packets
7:  Fwd Packet Length Max
8:  Fwd Packet Length Min
9:  Fwd Packet Length Mean
10:  Fwd Packet Length Std
11: Bwd Packet Length Max
12:  Bwd Packet Length Min
13:  Bwd Packet Length Mean
14:  Bwd Packet Length Std
15: Flow Bytes/s
16:  Flow Packets/s
17:  Flow IAT Mean
18:  Flow IAT Std
19:  Flow IAT Max
20:  Flow IAT Min
21: Fwd IAT Total
22:  Fwd IAT Mean
23:  Fwd IAT Std
24:  Fwd IAT Max
25:  Fwd IAT Min
26: Bwd IAT Total
27:  Bwd IAT Mean
28:  Bwd IAT Std
29:  Bwd IAT Max
30:  Bwd IAT Min
31: Fwd PSH Flags
32:  Bwd PSH Flags
33:  Fwd URG Flags
34:  Bwd URG Flags
35:  Fwd Header Length
36:  Bwd Header Length
37: Fwd Packets/s
38:  Bwd Packets/s
39:  Min Packet Length
40:  Max Packet Length
41:  Packet Length Mean
42:  Packet Length Std
43:  Packet Length Variance
44: FIN Flag Count
45:  SYN Flag Count
46:  RST Flag Count
47:  PSH Flag Count
48:  ACK Flag Count
49:  URG Flag Count
50:  CWE Flag Count
51:  ECE Flag Count
52:  Down/Up Ratio
53:  Average Packet Size
54:  Avg Fwd Segment Size
55:  Avg Bwd Segment Size
56:  Fwd Header Length.1
57: Fwd Avg Bytes/Bulk
58:  Fwd Avg Packets/Bulk
59:  Fwd Avg Bulk Rate
60:  Bwd Avg Bytes/Bulk
61:  Bwd Avg Packets/Bulk
62: Bwd Avg Bulk Rate
63: Subflow Fwd Packets
64:  Subflow Fwd Bytes
65:  Subflow Bwd Packets
66:  Subflow Bwd Bytes
67: Init_Win_bytes_forward
68:  Init_Win_bytes_backward
69:  act_data_pkt_fwd
70:  min_seg_size_forward
71: Active Mean
72:  Active Std
73:  Active Max
74:  Active Min
75: Idle Mean
76:  Idle Std
77:  Idle Max
78:  Idle Min
79:  Label

In [8]:
print(sample.columns[-1])

 Label

In [9]:
sample.columns = sample.columns.str.strip()

print(sample.columns.tolist())

['Destination Port', 'Flow Duration', 'Total Fwd Packets', 'Total Backward Packets', 'Total Length of Fwd Packets', 'Total Length of Bwd Packets', 'Fwd Packet Length Max', 'Fwd Packet Length Min', 'Fwd Packet Length Mean', 'Fwd Packet Length Std', 'Bwd Packet Length Max', 'Bwd Packet Length Min', 'Bwd Packet Length Mean', 'Bwd Packet Length Std', 'Flow Bytes/s', 'Flow Packets/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Total', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Total', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Length', 'Bwd Header Length', 'Fwd Packets/s', 'Bwd Packets/s', 'Min Packet Length', 'Max Packet Length', 'Packet Length Mean', 'Packet Length Std', 'Packet Length Variance', 'FIN Flag Count', 'SYN Flag Count', 'RST Flag Count', 'PSH Flag Count', 'ACK Flag Count', 'URG Flag Count', 'CWE Flag Count', 'ECE Flag Count', 'Down/Up Ratio', 'Average Packet Size', 'Avg Fwd Segment Size', 'Avg Bwd Segment Size', 'Fwd Header Length.1', 'Fwd Avg Bytes/Bulk', 'Fwd Avg Packets/Bulk', 'Fwd Avg Bulk Rate', 'Bwd Avg Bytes/Bulk', 'Bwd Avg Packets/Bulk', 'Bwd Avg Bulk Rate', 'Subflow Fwd Packets', 'Subflow Fwd Bytes', 'Subflow Bwd Packets', 'Subflow Bwd Bytes', 'Init_Win_bytes_forward', 'Init_Win_bytes_backward', 'act_data_pkt_fwd', 'min_seg_size_forward', 'Active Mean', 'Active Std', 'Active Max', 'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label']

In [10]:
from collections import Counter

label_counts = Counter()
file_rows = {}

for file in csv_files:
    print(f"Reading: {file.name}")

    file_count = 0

    for chunk in pd.read_csv(file, usecols=lambda c: c.strip() == "Label",
                             chunksize=100_000):

        chunk.columns = chunk.columns.str.strip()

        counts = chunk["Label"].value_counts()

        label_counts.update(counts.to_dict())
        file_count += len(chunk)

    file_rows[file.name] = file_count

print("\nFinished.")

Reading: Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv
Reading: Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv
Reading: Friday-WorkingHours-Morning.pcap_ISCX.csv
Reading: Monday-WorkingHours.pcap_ISCX.csv
Reading: Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv
Reading: Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv
Reading: Tuesday-WorkingHours.pcap_ISCX.csv
Reading: Wednesday-workingHours.pcap_ISCX.csv

Finished.

In [11]:
for filename, rows in file_rows.items():
    print(f"{filename}: {rows:,} rows")

Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv: 225,745 rows
Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv: 286,467 rows
Friday-WorkingHours-Morning.pcap_ISCX.csv: 191,033 rows
Monday-WorkingHours.pcap_ISCX.csv: 529,918 rows
Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv: 288,602 rows
Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv: 170,366 rows
Tuesday-WorkingHours.pcap_ISCX.csv: 445,909 rows
Wednesday-workingHours.pcap_ISCX.csv: 692,703 rows

In [12]:
print("Class distribution:\n")

for label, count in label_counts.most_common():
    print(f"{label}: {count:,}")

Class distribution:

BENIGN: 2,273,097
DoS Hulk: 231,073
PortScan: 158,930
DDoS: 128,027
DoS GoldenEye: 10,293
FTP-Patator: 7,938
SSH-Patator: 5,897
DoS slowloris: 5,796
DoS Slowhttptest: 5,499
Bot: 1,966
Web Attack � Brute Force: 1,507
Web Attack � XSS: 652
Infiltration: 36
Web Attack � Sql Injection: 21
Heartbleed: 11

In [13]:
class_distribution = pd.DataFrame(
    label_counts.items(),
    columns=["Label", "Count"]
)

class_distribution = class_distribution.sort_values(
    by="Count",
    ascending=False
).reset_index(drop=True)

class_distribution

                         Label    Count
0                       BENIGN  2273097
1                     DoS Hulk   231073
2                     PortScan   158930
3                         DDoS   128027
4                DoS GoldenEye    10293
5                  FTP-Patator     7938
6                  SSH-Patator     5897
7                DoS slowloris     5796
8             DoS Slowhttptest     5499
9                          Bot     1966
10    Web Attack � Brute Force     1507
11            Web Attack � XSS      652
12                Infiltration       36
13  Web Attack � Sql Injection       21
14                  Heartbleed       11

In [14]:
data_quality = []

for file in csv_files:
    print(f"Checking: {file.name}")

    df = pd.read_csv(file)
    df.columns = df.columns.str.strip()

    numeric_cols = df.select_dtypes(include=[np.number]).columns

    nan_count = df.isna().sum().sum()
    inf_count = np.isinf(df[numeric_cols]).sum().sum()
    duplicate_count = df.duplicated().sum()

    data_quality.append({
        "File": file.name,
        "Rows": len(df),
        "NaN": nan_count,
        "Infinity": inf_count,
        "Duplicates": duplicate_count
    })

quality_df = pd.DataFrame(data_quality)
quality_df

Checking: Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv
Checking: Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv
Checking: Friday-WorkingHours-Morning.pcap_ISCX.csv
Checking: Monday-WorkingHours.pcap_ISCX.csv
Checking: Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv
Checking: Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv
Checking: Tuesday-WorkingHours.pcap_ISCX.csv
Checking: Wednesday-workingHours.pcap_ISCX.csv

,File,Rows,NaN,Infinity,Duplicates
0,Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv,225745,4,64,2633
1,Friday-WorkingHours-Afternoon-PortScan.pcap_IS...,286467,15,727,72353
2,Friday-WorkingHours-Morning.pcap_ISCX.csv,191033,28,216,6888
3,Monday-WorkingHours.pcap_ISCX.csv,529918,64,810,26935
4,Thursday-WorkingHours-Afternoon-Infilteration....,288602,18,396,35630
5,Thursday-WorkingHours-Morning-WebAttacks.pcap_...,170366,20,250,6066
6,Tuesday-WorkingHours.pcap_ISCX.csv,445909,201,327,24065
7,Wednesday-workingHours.pcap_ISCX.csv,692703,1008,1586,81909

In [15]:
for file in csv_files:
    df = pd.read_csv(
        file,
        usecols=[" Fwd Header Length", " Fwd Header Length.1"]
    )

    df.columns = df.columns.str.strip()

    same = df["Fwd Header Length"].equals(
        df["Fwd Header Length.1"]
    )

    print(f"{file.name}: identical = {same}")

Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv: identical = True
Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv: identical = True
Friday-WorkingHours-Morning.pcap_ISCX.csv: identical = True
Monday-WorkingHours.pcap_ISCX.csv: identical = True
Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv: identical = True
Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv: identical = True
Tuesday-WorkingHours.pcap_ISCX.csv: identical = True
Wednesday-workingHours.pcap_ISCX.csv: identical = True

In [16]:
problem_columns = {}

for file in csv_files:
    print(f"\nChecking: {file.name}")

    df = pd.read_csv(file)
    df.columns = df.columns.str.strip()

    numeric_cols = df.select_dtypes(include=[np.number]).columns

    nan_by_column = df.isna().sum()
    nan_by_column = nan_by_column[nan_by_column > 0]

    inf_by_column = pd.Series(
        np.isinf(df[numeric_cols]).sum(),
        index=numeric_cols
    )
    inf_by_column = inf_by_column[inf_by_column > 0]

    print("NaN columns:")
    print(nan_by_column)

    print("\nInfinity columns:")
    print(inf_by_column)

    del df

Checking: Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv
NaN columns:
Flow Bytes/s    4
dtype: int64

Infinity columns:
Flow Bytes/s      30
Flow Packets/s    34
dtype: int64

Checking: Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv
NaN columns:
Flow Bytes/s    15
dtype: int64

Infinity columns:
Flow Bytes/s      356
Flow Packets/s    371
dtype: int64

Checking: Friday-WorkingHours-Morning.pcap_ISCX.csv
NaN columns:
Flow Bytes/s    28
dtype: int64

Infinity columns:
Flow Bytes/s       94
Flow Packets/s    122
dtype: int64

Checking: Monday-WorkingHours.pcap_ISCX.csv
NaN columns:
Flow Bytes/s    64
dtype: int64

Infinity columns:
Flow Bytes/s      373
Flow Packets/s    437
dtype: int64

Checking: Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv
NaN columns:
Flow Bytes/s    18
dtype: int64

Infinity columns:
Flow Bytes/s      189
Flow Packets/s    207
dtype: int64

Checking: Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv
NaN columns:
Flow Bytes/s    20
dtype: int64

Infinity columns:
Flow Bytes/s      115
Flow Packets/s    135
dtype: int64

Checking: Tuesday-WorkingHours.pcap_ISCX.csv
NaN columns:
Flow Bytes/s    201
dtype: int64

Infinity columns:
Flow Bytes/s       63
Flow Packets/s    264
dtype: int64

Checking: Wednesday-workingHours.pcap_ISCX.csv
NaN columns:
Flow Bytes/s    1008
dtype: int64

Infinity columns:
Flow Bytes/s       289
Flow Packets/s    1297
dtype: int64

In [17]:
duplicate_by_label = Counter()

for file in csv_files:
    print(f"Checking duplicates: {file.name}")

    df = pd.read_csv(file)
    df.columns = df.columns.str.strip()

    duplicates = df[df.duplicated(keep="first")]

    counts = duplicates["Label"].value_counts()
    duplicate_by_label.update(counts.to_dict())

    del df

print("\nDuplicate rows by label:\n")

for label, count in duplicate_by_label.most_common():
    print(f"{label}: {count:,}")

Checking duplicates: Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv
Checking duplicates: Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv
Checking duplicates: Friday-WorkingHours-Morning.pcap_ISCX.csv
Checking duplicates: Monday-WorkingHours.pcap_ISCX.csv
Checking duplicates: Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv
Checking duplicates: Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv
Checking duplicates: Tuesday-WorkingHours.pcap_ISCX.csv
Checking duplicates: Wednesday-workingHours.pcap_ISCX.csv

Duplicate rows by label:

BENIGN: 124,711
PortScan: 68,111
DoS Hulk: 58,224
SSH-Patator: 2,678
FTP-Patator: 2,005
DoS slowloris: 411
DoS Slowhttptest: 271
Web Attack � Brute Force: 37
Bot: 13
DDoS: 11
DoS GoldenEye: 7

In [18]:
duplicate_summary = []

for label, total_count in label_counts.items():

    duplicate_count = duplicate_by_label.get(label, 0)

    percentage = (
        duplicate_count / total_count * 100
        if total_count > 0
        else 0
    )

    duplicate_summary.append({
        "Label": label,
        "Total": total_count,
        "Duplicates": duplicate_count,
        "Duplicate_Percent": percentage
    })

duplicate_summary_df = pd.DataFrame(duplicate_summary)

duplicate_summary_df = duplicate_summary_df.sort_values(
    "Duplicate_Percent",
    ascending=False
).reset_index(drop=True)

duplicate_summary_df

                         Label    Total  Duplicates  Duplicate_Percent
0                  SSH-Patator     5897        2678          45.412922
1                     PortScan   158930       68111          42.855974
2                  FTP-Patator     7938        2005          25.258251
3                     DoS Hulk   231073       58224          25.197232
4                DoS slowloris     5796         411           7.091097
5                       BENIGN  2273097      124711           5.486391
6             DoS Slowhttptest     5499         271           4.928169
7     Web Attack � Brute Force     1507          37           2.455209
8                          Bot     1966          13           0.661241
9                DoS GoldenEye    10293           7           0.068007
10                        DDoS   128027          11           0.008592
11            Web Attack � XSS      652           0           0.000000
12                Infiltration       36           0           0.000000
13  Web Attack � Sql Injection       21           0           0.000000
14                  Heartbleed       11           0           0.000000

In [19]:
bad_rows_summary = []

for file in csv_files:
    df = pd.read_csv(file)
    df.columns = df.columns.str.strip()

    numeric_cols = df.select_dtypes(include=[np.number]).columns

    has_nan = df.isna().any(axis=1)
    has_inf = np.isinf(df[numeric_cols]).any(axis=1)

    bad_rows = has_nan | has_inf

    bad_rows_summary.append({
        "File": file.name,
        "Rows": len(df),
        "Rows_with_NaN": has_nan.sum(),
        "Rows_with_Infinity": has_inf.sum(),
        "Rows_with_any_problem": bad_rows.sum()
    })

    del df

bad_rows_df = pd.DataFrame(bad_rows_summary)
bad_rows_df

,File,Rows,Rows_with_NaN,Rows_with_Infinity,Rows_with_any_problem
0,Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv,225745,4,34,34
1,Friday-WorkingHours-Afternoon-PortScan.pcap_IS...,286467,15,371,371
2,Friday-WorkingHours-Morning.pcap_ISCX.csv,191033,28,122,122
3,Monday-WorkingHours.pcap_ISCX.csv,529918,64,437,437
4,Thursday-WorkingHours-Afternoon-Infilteration....,288602,18,207,207
5,Thursday-WorkingHours-Morning-WebAttacks.pcap_...,170366,20,135,135
6,Tuesday-WorkingHours.pcap_ISCX.csv,445909,201,264,264
7,Wednesday-workingHours.pcap_ISCX.csv,692703,1008,1297,1297